name: 3-5-secrets workflow

on: 
  workflow_dispatch:
  
jobs:
  secrets-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Show secret number
        run: echo "${{ secrets.SAMPLE_SECRET }}"