name: Hello workflow

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run job1
        run: echo "first job"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Run job2
        run: echo "second job"
    needs: job1